default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kanpai_development

test:
  <<: *default
  database: kanpai_test

production:
  <<: *default
  database: kanpai_production
  username: kanpai
  password: <%= ENV['KANPAI_DATABASE_PASSWORD'] %>
